spring:
  application:
    name: exampleApp
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: dev
  data:
    mongodb:
      database: identity
  security:
    user:
      name: admin
      password: admin123

server:
  port: 8080

aws:
  accessKeyId: AKIAZ24ISVUHQCAOKGOA
  secretKey: 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